// s../error-management/ErrorTypes.js

export class ErrorTypes {
  // سطوح عمومی که برای لاگ و تصمیم‌گیری استفاده می‌شوند
  static BROWSER_API_UNAVAILABLE = "BROWSER_API_UNAVAILABLE";
  static HTTP_ERROR = "HTTP_ERROR";
  static NETWORK_ERROR = "NETWORK_ERROR";
  static API_RESPONSE_INVALID = "API_RESPONSE_INVALID";
  static SERVICE = "SERVICE";
  static VALIDATION = "VALIDATION";
  static TAB_AVAILABILITY = "TAB";
  static CONTEXT = "CONTEXT";
  static EXTENSION_CONTEXT_INVALIDATED = "EXTENSION_CONTEXT_INVALIDATED";
  static PAGE_MOVED_TO_CACHE = "PAGE_MOVED_TO_CACHE";
  static CONNECTION_LOST = "CONNECTION_LOST";
  static UI = "UI";
  static INTEGRATION = "INTEGRATION";
  static SUBTITLE = "SUBTITLE";
  static SCREEN_CAPTURE = "SCREEN_CAPTURE";
  static UNKNOWN = "UNKNOWN";
  static SELECT_ELEMENT = "SELECT_ELEMENT";
  static NODE_ALREADY_TRANSLATED = "NODE_ALREADY_TRANSLATED";

  // Tab Accessibility errors
  static TAB_RESTRICTED = "TAB_RESTRICTED";
  static TAB_BROWSER_INTERNAL = "TAB_BROWSER_INTERNAL";
  static TAB_EXTENSION_PAGE = "TAB_EXTENSION_PAGE";
  static TAB_LOCAL_FILE = "TAB_LOCAL_FILE";
  static TAB_NOT_ACCESSIBLE = "TAB_NOT_ACCESSIBLE";


  // کلیدهای اعتبارسنجی (همان errorKeys بدون پیشوند ERRORS_)
  static PROMPT_INVALID = "PROMPT_INVALID";
  static TEXT_EMPTY = "TEXT_EMPTY";
  static TEXT_TOO_LONG = "TEXT_TOO_LONG";
  static TRANSLATION_NOT_FOUND = "TRANSLATION_NOT_FOUND";
  static TRANSLATION_FAILED = "TRANSLATION_FAILED";
  static TRANSLATION_ERROR = "TRANSLATION_ERROR";
  static TRANSLATION_TIMEOUT = "TRANSLATION_TIMEOUT";
  static SETTINGS_LOADING_TIMEOUT = "SETTINGS_LOADING_TIMEOUT";
  static LANGUAGE_PAIR_NOT_SUPPORTED = "LANGUAGE_PAIR_NOT_SUPPORTED";
  static USER_CANCELLED = "USER_CANCELLED";
  static TRANSLATION_CANCELLED = "TRANSLATION_CANCELLED";
  static PAGE_TRANSLATION_STOPPED = "PAGE_TRANSLATION_STOPPED";

  // Provider-specific response errors
  static HTML_RESPONSE_ERROR = "HTML_RESPONSE_ERROR";
  static JSON_PARSING_ERROR = "JSON_PARSING_ERROR";
  static UNEXPECTED_RESPONSE_FORMAT = "UNEXPECTED_RESPONSE_FORMAT";

  // تنظیمات API
  static API_KEY_MISSING = "API_KEY_MISSING";
  static API_KEY_INVALID = "API_KEY_INVALID";
  static API_URL_MISSING = "API_URL_MISSING";
  static API_ENDPOINT_INVALID = "API_ENDPOINT_INVALID";
  static MODEL_MISSING = "MODEL_MISSING";
  static MODEL_OVERLOADED = "MODEL_OVERLOADED";
  static QUOTA_EXCEEDED = "QUOTA_EXCEEDED";
  static INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE";
  static FORBIDDEN_ERROR = "FORBIDDEN_ERROR";
  static INVALID_REQUEST = "INVALID_REQUEST";
  static GEMINI_QUOTA_REGION = "GEMINI_QUOTA_REGION";
  static SERVER_ERROR = "SERVER_ERROR";
  static RATE_LIMIT_REACHED = "RATE_LIMIT_REACHED"; // برای خطای 429
  static CIRCUIT_BREAKER_OPEN = "CIRCUIT_BREAKER_OPEN";

  // DeepL-specific errors
  static DEEPL_QUOTA_EXCEEDED = "DEEPL_QUOTA_EXCEEDED"; // HTTP 456 - DeepL character limit

  // Import/Export password errors
  static IMPORT_PASSWORD_REQUIRED = "IMPORT_PASSWORD_REQUIRED";
  static IMPORT_PASSWORD_INCORRECT = "IMPORT_PASSWORD_INCORRECT";

  // Screen Capture specific errors
  static SCREEN_CAPTURE_FAILED = "SCREEN_CAPTURE_FAILED";
  static SCREEN_CAPTURE_PERMISSION_DENIED = "SCREEN_CAPTURE_PERMISSION_DENIED";
  static SCREEN_CAPTURE_NOT_SUPPORTED = "SCREEN_CAPTURE_NOT_SUPPORTED";
  static IMAGE_PROCESSING_FAILED = "IMAGE_PROCESSING_FAILED";
  static PROVIDER_IMAGE_NOT_SUPPORTED = "PROVIDER_IMAGE_NOT_SUPPORTED";

  // TTS specific errors
  static TTS = "TTS";
  static TTS_STOP_FAILED = "TTS_STOP_FAILED";
  static TTS_OFFSCREEN_CLOSED = "TTS_OFFSCREEN_CLOSED";
  static TTS_NO_RESPONSE = "TTS_NO_RESPONSE";
}
